### PR TITLE
darksouls3_profiles to eldenring_profiles

### PR DESCRIPTION
**Pull request by JustAnOkapi**
just a single quick rename

### CODE REVIEW

**Comment by JustAnOkapi** [comment]
did you mean to put the map in here?

**Review by JustAnOkapi — COMMENTED** [review]
overridden in next commit anyways

**Review by JustAnOkapi — COMMENTED** [review]
this will reset peoples current theme but once set again it still works

**Comment by azy2** [comment]
We can't change this because it will delete everyone's saved progress.

**Pull request closed without merging**
