### PR TITLE
Checkbox linking

### PR DESCRIPTION
**Pull request by wdya**
Added a bunch of links between checkboxes up and down the NPC Questlines page. Left a comment explaining each one so they're easy to interpret without cross-referencing. Feel free to veto any of them. Also tweaked some typos and stuff on the quests page.

### CODE REVIEW

**Comment by azy2** [comment]
The code looks great. I don't have time to manually cross check each entry to see if they *should* be linked. Either someone else can review this or I can take your word for it and merge.

**Review by ATH42 — APPROVED** [review]
all links look good to me! 👍🏼

**Review by ATH42 — APPROVED** [review]
tested local. 

everything is correctly linked.

**Comment by azy2** [comment]
I'm sorry I dropped the ball on this one. But now it's out of date with the changes to walkthrough/npc quests.

**Pull request closed without merging**
